# Generated by Django 4.2.30 on 2026-06-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ka', models.CharField(blank=True, max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('title_ka', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('subtitle_ka', models.CharField(blank=True, max_length=400)),
                ('subtitle_en', models.CharField(blank=True, max_length=400)),
                ('cta_text_ka', models.CharField(blank=True, max_length=100)),
                ('cta_text_en', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ka', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home Page'), ('menu', 'Menu Page'), ('salumeria', 'Salumeria Page')], max_length=50, unique=True)),
                ('title_ka', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('description_ka', models.TextField(blank=True, max_length=500)),
                ('description_en', models.TextField(blank=True, max_length=500)),
                ('keywords', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('tagline_ka', models.CharField(default='დაბადებული იტალიაში, გამომცხვარი თბილისში', max_length=200)),
                ('tagline_en', models.CharField(default='Born in Italy, Baked in Tbilisi', max_length=200)),
                ('phone', models.CharField(default='+995 598 80 00 45', max_length=50)),
                ('address_ka', models.CharField(default='თბილისი, ძველი ქალაქი', max_length=300)),
                ('address_en', models.CharField(default='Tbilisi, Old Town', max_length=300)),
                ('opening_hours_ka', models.TextField(default='ორშ–პარ: 11:00–22:00\nშაბ–კვი: 10:00–23:00')),
                ('opening_hours_en', models.TextField(default='Mon–Fri: 11:00–22:00\nSat–Sun: 10:00–23:00')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/focacceria.ge')),
                ('whatsapp', models.CharField(blank=True, default='+995598800045', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('google_maps_url', models.URLField(blank=True)),
                ('wolt_url', models.URLField(blank=True)),
                ('glovo_url', models.URLField(blank=True)),
                ('about_title_ka', models.CharField(blank=True, default='ჩვენს შესახებ', max_length=200)),
                ('about_title_en', models.CharField(blank=True, default='About Us', max_length=200)),
                ('about_text_ka', models.TextField(blank=True)),
                ('about_text_en', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ka', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footercolumn')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
