# Generated by Django 4.2.30 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_iframe_url',
            field=models.URLField(blank=True, default='https://focacceria.eat-me.online/en/category/mortadella'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='menu_loader_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
