# Generated by Django 4.2.30 on 2026-06-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_menu_iframe_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_call_icon',
            field=models.CharField(blank=True, default='📞', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_glovo_icon',
            field=models.CharField(blank=True, default='🟡', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_maps_icon',
            field=models.CharField(blank=True, default='📍', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_whatsapp_icon',
            field=models.CharField(blank=True, default='💬', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_wolt_icon',
            field=models.CharField(blank=True, default='🛵', max_length=20),
        ),
    ]
