# Generated by Django 4.2.30 on 2026-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_delivery_call_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
    ]
