# Generated by Django 4.2.30 on 2026-06-04 16:50

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_heroslide_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FontSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_font_en_name', models.CharField(default='Anton', max_length=120)),
                ('heading_font_en_url', models.URLField(blank=True, default='https://fonts.googleapis.com/css2?family=Anton&display=swap')),
                ('body_font_en_name', models.CharField(default='Inter', max_length=120)),
                ('body_font_en_url', models.URLField(blank=True, default='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap')),
                ('heading_font_ka_name', models.CharField(default='Noto Sans Georgian', max_length=120)),
                ('heading_font_ka_file', models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['woff', 'woff2', 'ttf', 'otf']), core.models.validate_max_font_size])),
                ('body_font_ka_name', models.CharField(default='Noto Sans Georgian', max_length=120)),
                ('body_font_ka_file', models.FileField(blank=True, null=True, upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['woff', 'woff2', 'ttf', 'otf']), core.models.validate_max_font_size])),
            ],
            options={
                'verbose_name': 'Font Settings',
            },
        ),
        migrations.CreateModel(
            name='HomeVideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('effect', models.CharField(choices=[('split', 'Split Reveal'), ('parallax', 'Parallax Reveal')], default='split', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='home-video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v']), core.models.validate_max_video_size])),
                ('title_ka', models.CharField(blank=True, default='როგორ მზადდება გემო', max_length=220)),
                ('title_en', models.CharField(blank=True, default='Where flavor gets made', max_length=220)),
                ('subtitle_ka', models.TextField(blank=True, default='საფირმო შრეები, ტექსტურა და იტალიური ინგრედიენტები — ისე, თითქოს შენს თვალწინ მზადდება ყველაფერი.')),
                ('subtitle_en', models.TextField(blank=True, default='Signature layers, texture, and Italian ingredients — revealed as if the food is being prepared in front of you.')),
            ],
            options={
                'verbose_name': 'Home Video Section',
            },
        ),
    ]
