# Generated by Django 6.0.6 on 2026-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fontsettings_homevideosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='marquee_text_en',
            field=models.CharField(default='SCHIACCIATA SANDWICHES · SALUMERIA CORNER · BORN IN ITALY · BAKED IN TBILISI', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='marquee_text_ka',
            field=models.CharField(default='SCHIACCIATA SANDWICHES · SALUMERIA CORNER · BORN IN ITALY · BAKED IN TBILISI', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_about',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_marquee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_visit',
            field=models.BooleanField(default=True),
        ),
    ]
