# Generated by Django 6.0.6 on 2026-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_marquee_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='story_kicker_en',
            field=models.CharField(blank=True, default='Our Story', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_kicker_ka',
            field=models.CharField(blank=True, default='ჩვენი ისტორია', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_subtitle_en',
            field=models.TextField(blank=True, default='Italian technique and ingredients — with Tbilisi rhythm.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_subtitle_ka',
            field=models.TextField(blank=True, default='იტალიური ტექნიკა და ინგრედიენტები — თბილისის რიტმით.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_title_en',
            field=models.CharField(blank=True, default='Italy + Tbilisi', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='story_title_ka',
            field=models.CharField(blank=True, default='იტალია + თბილისი', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_kicker_en',
            field=models.CharField(blank=True, default='Visit', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_kicker_ka',
            field=models.CharField(blank=True, default='ვიზიტი', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_subtitle_en',
            field=models.TextField(blank=True, default='Open today · Old Town, Tbilisi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_subtitle_ka',
            field=models.TextField(blank=True, default='დღეს ღიაა · ძველი ქალაქი, თბილისი'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_title_en',
            field=models.CharField(blank=True, default='Come, eat well', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='visit_title_ka',
            field=models.CharField(blank=True, default='მოდი, კარგად ჭამეთ', max_length=200),
        ),
    ]
