# Generated by Django 6.0.6 on 2026-06-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sitesettings_story_kicker_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='salumeria_kicker_en',
            field=models.CharField(blank=True, default='Salumeria', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='salumeria_kicker_ka',
            field=models.CharField(blank=True, default='სალუმერია', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='salumeria_lead_en',
            field=models.TextField(blank=True, default='Cold cuts, cheese, oils and packages — order with WhatsApp.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='salumeria_lead_ka',
            field=models.TextField(blank=True, default='ხორცეული, ყველი, ზეთები და ნაკრები — შეკვეთა WhatsApp-ით.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='salumeria_title_en',
            field=models.CharField(blank=True, default='Italian delicacies to take home', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='salumeria_title_ka',
            field=models.CharField(blank=True, default='იტალიური დელიკატესები სახლში წასაღებად', max_length=200),
        ),
    ]
