# Generated by Django 6.0.6 on 2026-06-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_salumeria_kicker_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_menu_products',
            field=models.BooleanField(default=True),
        ),
    ]
