# Generated by Django 6.0.6 on 2026-06-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_show_menu_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_message_en',
            field=models.CharField(blank=True, default='How can we help you?', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_message_ka',
            field=models.CharField(blank=True, default='რითი დაგეხმაროთ?', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
