# Generated by Django 6.0.6 on 2026-06-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_whatsapp_widget_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_btn_en',
            field=models.CharField(blank=True, default='Message Us', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_btn_ka',
            field=models.CharField(blank=True, default='მიწერა', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_name_en',
            field=models.CharField(blank=True, default='Focacceria Support', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_widget_name_ka',
            field=models.CharField(blank=True, default='Focacceria Support', max_length=100),
        ),
    ]
