# Generated by Django 6.0.6 on 2026-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_whatsapp_widget_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS injected before </head> on every page. No <style> tags needed.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='custom_js',
            field=models.TextField(blank=True, help_text='Custom JavaScript injected before </body> on every page. No <script> tags needed.'),
        ),
    ]
