# Generated by Django 6.0.6 on 2026-06-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_custom_css_sitesettings_custom_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='quick_cta_en',
            field=models.CharField(blank=True, default='Go to Menu', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_cta_ka',
            field=models.CharField(blank=True, default='მენიუზე გადასვლა', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_kicker_en',
            field=models.CharField(blank=True, default='About Us', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_kicker_ka',
            field=models.CharField(blank=True, default='ჩვენ შესახებ', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_lead_en',
            field=models.TextField(blank=True, default='Made with original Italian recipes, in the heart of Tbilisi — we craft schiacciata sandwiches that taste like Italy.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_lead_ka',
            field=models.TextField(blank=True, default='ორიგინალი იტალიური რეცეპტებითა და თბილისის გულში — ჩვენ ვამზადებთ schiacciata სენდვიჩებს, რომლებიც გაგახსენებთ იტალიას.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_title_en',
            field=models.CharField(blank=True, default='Our Story', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='quick_title_ka',
            field=models.CharField(blank=True, default='ჩვენი ამბავი', max_length=200),
        ),
    ]
