# Generated by Django 6.0.6 on 2026-06-30 15:07

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_quick_cta_en_sitesettings_quick_cta_ka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional. If set, this video plays in the hero background instead of the image. Separate from the "How it\'s made" video.', null=True, upload_to='hero-video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v']), core.models.validate_max_video_size]),
        ),
    ]
