# Generated by Django 6.0.6 on 2026-06-30 15:44

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_heroslide_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='video_file',
        ),
        migrations.AddField(
            model_name='homevideosection',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='Hero (top of homepage) background video. Separate from the Culinary Moment video above.', null=True, upload_to='home-video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v']), core.models.validate_max_video_size]),
        ),
        migrations.AlterField(
            model_name='homevideosection',
            name='video_file',
            field=models.FileField(blank=True, help_text='Culinary Moment ("How it\'s made") section video.', null=True, upload_to='home-video/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v']), core.models.validate_max_video_size]),
        ),
    ]
