# Generated by Django 4.2.30 on 2026-06-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description_ka', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('page', models.CharField(choices=[('menu', 'Menu'), ('salumeria', 'Salumeria')], default='menu', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ka', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_ka', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_unit', models.CharField(blank=True, choices=[('', 'ერთეული'), ('100g', '100 გრ'), ('portion', 'პორცია')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags: vegan, vegetarian, spicy, new', max_length=200)),
                ('badge_ka', models.CharField(blank=True, help_text='e.g. ახალი, ყველაზე პოპ.', max_length=50)),
                ('badge_en', models.CharField(blank=True, help_text='e.g. New, Most Popular', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
